### PR TITLE
Adds docs for custom field item filter resources

### PR DESCRIPTION
**Pull request by mcrosby114**
Exposes documentation on three resources:
- `custom field item filters`
- `custom field item jobcode filters`
- `custom field item user filters`

### CODE REVIEW

**Comment by peterfunk** [comment]
Looks good to me.  I applied the patch to a local copy of Matt's fork, built it with docker, and verified the changes in my local browser.  I did notice some funky characters in the timestamp format strings but I expect it is an encoding issue as opposed to an actual issue with the PR.  For example:

`(YYYY-MM-DDThh:mm:ssÂ±hh:mm)`

**Comment by dustinsweet** [comment]
What would you guys think of putting all new content under the single navbar section "Custom Field Item Filters?"  I realize you're adding different resources, but we could consider the sections categories.  I'm concerned that adding three new sections takes up too much vertical space and makes it look like Custom Fields are taking over the world (or at least our API.  Lisa Patel agrees, fwiw :) )

If you decide to keep 3, consider widening the navbar so the full text displays. Edit the _variables.scss file and set to 260px (line 59):  `$nav-width: 260px !default; // width of the navbar`

**Comment by dustinsweet** [comment]
+1 on Peter's comment for the time format, needs fixing.  Weird char displays not just in markdown, but also in the compiled docs.

**Comment by mcrosby114** [comment]
https://github.com/TSheetsTeam/api_docs/pull/29#issuecomment-501860649 it looks like weird symbol was due to the html encoding -- needs to use UTF-8. That was also affecting a bunch of other endpoint docs that use the ± symbol

**Comment by mcrosby114** [comment]
@dustinsweet I see what you mean with how the names start to pile up; the user and jobcode filter objects are closely related to the main item filter, just more specific, but they're all basically serving the same purpose.

Was this roughly what you had in mind for how it would look? 
Screen Shot 2019-06-13 at 4 40 01 PM


Is there a better way to indicate the hierarchy of the three different resources if you combine all three under the "Custom Field Item Filters" section?

Perhaps we could support one more level of nesting [as described here](https://github.com/lord/slate/wiki/Deeper-Nesting).... So it could look like:
```
Custom Field Item Filters
---- ---- The Item Filter Object
---- ---- Retrieve Item Filters
---- Custom Field Item Jobcode Filters
---- ---- The Jobcode Filter Object
---- ---- Retrieve Jobcode Filters
---- Custom Field Item User Filters
---- ---- The User Filter Object
---- ---- Retrieve User Filters
```

**Comment by dustinsweet** [comment]
Yes, exactly.  The image of the navbar menu is what I had in mind.  As far as the deeper nesting goes, I gave that link a try a while back and found it to be lacking.  Something with the UI - navbar menu auto-expansion stopped working, or maybe it was some scrolling issue, can't recall.

**Comment by mcrosby114** [comment]
Here's what it looks like now with a 240px toc width
Screen Shot 2019-06-18 at 1 38 54 PM

**Review by dustinsweet — APPROVED** [review]
Looks good to me.  Thanks Matt!

**Pull request merged**
