### PR TITLE
Readme file uses new QB Time logo

### PR DESCRIPTION
**Pull request by evanhsu**
Hey @int-gaguilar1 !
Love the new look 😍 
I added your totally sick new QB Time svg logo to the readme file for fun ~and profit~

There's a little bit of white text on white background going on, but without adding an additional SVG with contrasting colors, I don't think there's a way to re-color the existing SVG in Github-flavored markdown since `style` properties aren't allowed. 🤷🏻‍♂️ 

**Test Plan**
  - Check out this branch locally and open the readme in your favorite markdown viewer (I use markdown preview in VS Code)

### CODE REVIEW

**Comment by int-gaguilar1** [comment]
@evanhsu awesome I will get on this review shortly. Thanks for adding the new logo ☕

**Comment by int-gaguilar1** [comment]
Nice work on this Evan thanks for your awesome contribution. I can add the center attribute for the `p` tag in the README.md file and that will match what we have on the master branch. Once you merge it I can then ask @dustinsweet which image we would like but I think this should be fine. We update the introduction with `TSheets is now QuickBooks Time` there. Have a great day and week and thanks again for your awesome contribution ☕ 

I just reread and looked at the change and it aligned to the left my bad need more coffee looks good :-)

**Review by int-gaguilar1 — APPROVED** [review]
Looks great merge that and I will update the _update file. I just downloaded the zip file and opened the file in vs code and added the new extension. Thanks for the heads up on that extension it is pretty cool. Cheers ☕

**Comment by int-gaguilar1** [comment]
@evanhsu I am looking at the logo and know we have a different one for our white background as well. Would you like to close this PR and I can then create a new story or send you the correct image? I got all excited and approved before checking on the image.

**Comment by evanhsu** [comment]
I've allowed edits by maintainers on this branch, so you can push the new image directly to this branch and then I'll update the markdown 👍🏻

**Comment by int-gaguilar1** [comment]
Thanks @evanhsu we just added the new image and got it out it is now updated. I did forget to save on the badge that is seen `TSheets Developer`. We will add that to the story that is open for updating all of the text. Cheers and have a great weekend ☕

**Pull request closed without merging**
