### PR TITLE
Change notes for display_name and pronouns

### PR DESCRIPTION
**Pull request by brikr**
These fields are no longer null if the GED_INCLUSION feature gate is disabled. They are an empty string instead.

### CODE REVIEW

**Review by EldinTurulja — CHANGES_REQUESTED** [review]
Can you just update the changelog section as well. Sorry that part is tedious. Otherwise this looks good to me.

**Comment by brikr** [comment]
Sure thing 👍 it is done

**Review by EldinTurulja — APPROVED** [review]
Thank you! LGTM

**Comment by elloboblanco** [comment]
Who owns shipping this? Can we get @EldinTurulja or @brikr to?

**Pull request merged**
